CREATE TABLE [dbo].[Order]
(
	[Id] INT NOT NULL PRIMARY KEY, 
	[ShippedDate] DATETIME NULL, 
	[CreatedDate] DATETIME NOT NULL DEFAULT GETUTCDATE(), 
	[CreatedBy] NVARCHAR(50) NOT NULL DEFAULT 'System',
	[UpdatedDate] DATETIME NOT NULL DEFAULT GETUTCDATE(), 
	[UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT 'System'
)
